--- #YAML:1.0
name:               WWW-Live-Contacts
version:            1.0.0
abstract:           A Microsoft Live Contacts client
author:
    - Andrew M. Jenkinson <jenkinson@cpan.org>
license:            lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:           0
    Crypt::SSLeay:  0
    LWP:            0
    XML::Simple:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
